name: aahitest
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
#  cloud_firestore: ^0.13.5
  cupertino_icons: ^0.1.2
  device_info: ^0.4.2+3
  extended_tabs: ^0.2.3
  firebase_analytics: ^5.0.9
  firebase_crashlytics: ^0.1.2+5
  firebase_auth: ^0.16.0
  firebase_messaging: ^6.0.13
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_map: ^0.9.0
  flutter_svg: ^0.17.4
  http: ^0.12.0+2
  location: ^3.0.2
  path_provider: ^1.6.10
  quiver: ^2.1.3
  shared_preferences: ^0.5.6+1
  validate: ^1.6.0
  package_info: 0.4.1
  version: ^1.0.3
  launch_review: ^2.0.0
  flutter_grid_delegate_ext: ^0.0.2
  open_file: ^3.0.1
  worker_manager: 2.3.4
  photo_view:
    git:
      url: https://github.com/autolainen/photo_view.git
      ref: "master"
  rxdart: ^0.24.0
  local_auth: ^0.6.1
  pin_code_text_field: ^1.5.1
  hive: ^1.4.1+1
  hive_flutter: ^0.3.0+2
  sms_receiver: ^0.3.1+1
  pedantic: ^1.9.0
  animations: 1.1.0
  intl: ^0.16.0
  collection: ^1.14.11
  data_model:
    git:
      url: https://gitlab.com/dartrest/data_model.git
      ref: "master"
  dartz: ^0.8.7
  expressions: ^0.1.2
  mime: ^0.9.6+3
  equatable: ^1.2.0
  get_it: ^4.0.2
  event_bus: ^1.1.0
  url_launcher: ^5.4.5

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
